# yaml-language-server: $schema=https://raw.githubusercontent.com/streetsidesoftware/cspell/main/packages/cspell-tools/cspell-tools.config.schema.json

targets:
  - name: 'be_by'
    sources:
      - src/additional_words.txt
      - src/hunspell/index.dic
    format: 'trie3'
    targetDirectory: './dict'
    generateNonStrict: true
    compress: true
checksumFile: true
